

import platform
import os

DEV_MODE = platform.system() != "Linux"  # DEVMODE ON WINDOWS, NOTDEVMODE ON LINUX

CAMERA_WIDTH = 1280
CAMERA_HEIGHT = 720

STREAM_FRAME_RATE = 10

CAM_FORMAT = "RGB888"

SERVER_PORT = 5000
SHOW_PREVIEW = DEV_MODE



RESOLUTION = (CAMERA_WIDTH, CAMERA_HEIGHT)

#FALLBACK IMAGE FOR DEV
# DEV_IMAGE_PATH = "test/fallback/6.jpg"